// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjg7zau-KiKPZzcCwxKH1eiVRg6f2S45o',
    appId: '1:702239386555:web:96cfb16567d761490e729e',
    messagingSenderId: '702239386555',
    projectId: 'ksdpl-app',
    authDomain: 'ksdpl-app.firebaseapp.com',
    storageBucket: 'ksdpl-app.firebasestorage.app',
    measurementId: 'G-SMFC2ZGVLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwtDDuhHNQ7yvqcArpPj-X8B0vUdV8Nc',
    appId: '1:702239386555:android:0f4c91e05ea907740e729e',
    messagingSenderId: '702239386555',
    projectId: 'ksdpl-app',
    storageBucket: 'ksdpl-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-kU3hzkvrWjk9R9WDtQ55odCZL3v3gA',
    appId: '1:702239386555:ios:0bf675adbd51ce4a0e729e',
    messagingSenderId: '702239386555',
    projectId: 'ksdpl-app',
    storageBucket: 'ksdpl-app.firebasestorage.app',
    iosBundleId: 'com.ns.ksdpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-kU3hzkvrWjk9R9WDtQ55odCZL3v3gA',
    appId: '1:702239386555:ios:0bf675adbd51ce4a0e729e',
    messagingSenderId: '702239386555',
    projectId: 'ksdpl-app',
    storageBucket: 'ksdpl-app.firebasestorage.app',
    iosBundleId: 'com.ns.ksdpl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjg7zau-KiKPZzcCwxKH1eiVRg6f2S45o',
    appId: '1:702239386555:web:20dba874016015e30e729e',
    messagingSenderId: '702239386555',
    projectId: 'ksdpl-app',
    authDomain: 'ksdpl-app.firebaseapp.com',
    storageBucket: 'ksdpl-app.firebasestorage.app',
    measurementId: 'G-WNNBDBJX5D',
  );
}
